/**
 * 反射工具类
 */
var Reflect = {
    isInt: Native.Reflect.isInt,
    isDouble: Native.Reflect.isDouble,
    isBool: Native.Reflect.isBool,
    isString: Native.Reflect.isString,
    isList: Native.Reflect.isList,
    isObject: Native.Reflect.isObject,
    isUndefined: Native.Reflect.isUndefined,
    hashCode: Native.Reflect.hashCode,
    fields: Native.Reflect.fields,
    setField: Native.Reflect.setField,
    getField: Native.Reflect.getField,
    hasField: Native.Reflect.hasField
}