function permutation(nums) {
    var result = []
                
    var book = []
    for (var i = 0; i < nums.length(); i++) {
        book.addLast(false)
    }
                
    var p = []
    function dfs(index) {
        if (index == nums.length()) {
            result.addLast(p.copy())
            return
        }
                
        for (var i = 0; i < nums.length(); ++i) {
            if (!book[i]) {
                book[i] = true
                p.addLast(nums[i])
                dfs(index + 1)
                p.removeLast()
                book[i] = false
            }
        }
    }
                
    dfs(0)
                
    return result
}

function permutation2(nums) {
    var result = Set()

    var book = []
    for (var i = 0; i < nums.length(); i++) {
        book.addLast(false)
    }

    var p = []
    function dfs(index) {
        if (index == nums.length()) {
            result.add(p.copy())
            return
        }

        for (var i = 0; i < nums.length(); ++i) {
            if (!book[i]) {
                book[i] = true
                p.addLast(nums[i])
                dfs(index + 1)
                p.removeLast()
                book[i] = false
            }
        }
    }

    dfs(0)

    return result.toList()
}

var result1 = permutation([1, 2, 3])
for (var i = 0; i < result1.length(); ++i) {
    Console.println(result1[i])
}

var result2 = permutation2([1, 1, 2])
for (var i = 0; i < result2.length(); ++i) {
    Console.println(result2[i])
}

var result3 = permutation2([1, 1, 3, 3])
for (var i = 0; i < result3.length(); ++i) {
    Console.println(result3[i])
}
